### PR TITLE
Fixed use of deprecated methods in sample app project

### PR DESCRIPTION
**Pull request by TheRealAgentK**
Fixed use of deprecated methods in sample app project

### CODE REVIEW

**Comment by TheRealAgentK** [comment]
Hey guys - any reason why you don't merge my PR?

**Comment by CmdrKeen** [comment]
Good Q @TheRealAgentK - will check with @fundead

**Comment by fundead** [comment]
cc @mduncan26

**Comment by fundead** [comment]
Hey Kai, this one was considered medium priority as it was fixing deprecated yet supported methods in a sample app, and as the merge requires a release time needed to be made available for that, and other scheduled work was prioritized. I'll be releasing this today but going forward there others on the team will be maintaining this repository.

**Pull request merged**
